project_id = "ndvuxiynbrklugcunxts"

[functions.paypal-create-order]
verify_jwt = false

[functions.paypal-capture-order]
verify_jwt = false

[functions.pod-route-order]
verify_jwt = false

[functions.webhook-printful]
verify_jwt = false

[functions.track]
verify_jwt = false

[functions.generate-description]
verify_jwt = false

[functions.monitor]
verify_jwt = false

[functions.shipping-rate]
verify_jwt = false
